AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
AddCSLuaFile("client/client_init.lua")
AddCSLuaFile("client/hud.lua")
AddCSLuaFile("client/chat.lua")
AddCSLuaFile("shared/shared_init.lua")
 
include("server/chat.lua")
include("server/server_init.lua")
include("shared.lua")